spring:
  datasource:
    username: root #???
    url: jdbc:mysql://localhost:3306/timeflow
    password: root #??
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:example/demo/mapper/*Mapper.xml
  type-aliases-package: example.demo